#!/bin/sh
set -e

export KUBECONFIG="$1"
ASSETS_PATH="$2"

# Setup API Authentication
KUBECTL="/kubectl --kubeconfig=$KUBECONFIG"

# Setup helper functions

kubectl() {
  i=0

  echo "Executing kubectl" "$@"
  while true; do
    i=$((i+1))
    [ $i -eq 100 ] && echo "kubectl failed, giving up" && exit 1

    set +e
    out=$($KUBECTL "$@" 2>&1)
    status=$?
    set -e

    if echo "$out" | grep -q "AlreadyExists"; then
      echo "$out, skipping"
      return
    fi

    echo "$out"
    if [ "$status" -eq 0 ]; then
      return
    fi

    echo "kubectl failed, retrying in 5 seconds"
    sleep 5
  done
}

wait_for_crd() {
  set +e
  i=0

  echo "Waiting for CRD $2"
  until $KUBECTL -n "$1" get customresourcedefinition "$2"; do
    i=$((i+1))
    echo "CRD $2 not available yet, retrying in 5 seconds ($i)"
    sleep 5
  done
  set -e
}

wait_for_tpr() {
  set +e
  i=0

  echo "Waiting for TPR $2"
  until $KUBECTL -n "$1" get thirdpartyresources "$2"; do
    i=$((i+1))
    echo "TPR $2 not available yet, retrying in 5 seconds ($i)"
    sleep 5
  done
  set -e
}

wait_for_pods() {
  set +e
  echo "Waiting for pods in namespace $1"
  while true; do

    out=$($KUBECTL -n "$1" get po -o custom-columns=STATUS:.status.phase,NAME:.metadata.name)
    status=$?
    echo "$out"

    if [ "$status" -ne "0" ]; then
      echo "kubectl command failed, retrying in 5 seconds"
      sleep 5
      continue
    fi

    # make sure kubectl does not return "no resources found"
    if [ "$(echo "$out" | tail -n +2 | grep -c '^')" -eq 0 ]; then
      echo "no resources were found, retrying in 5 seconds"
      sleep 5
      continue
    fi

    stat=$(echo "$out"| tail -n +2 | grep -v '^Running')
    if [ -z "$stat" ]; then
      return
    fi

    echo "Pods not available yet, waiting for 5 seconds"
    sleep 5
  done
  set -e
}

asset_cleanup() {
  echo "Cleaning up installation assets"

  # shellcheck disable=SC2034
  for d in "manifests" "auth" "tectonic" "tls"; do
      rm -rf "$${ASSETS_PATH:?}/$${d:?}/"*
  done

  # shellcheck disable=SC2034
  for f in "bootkube.sh" "tectonic.sh" "tectonic-wrapper.sh"; do
      rm -f "$${ASSETS_PATH:?}/$${f:?}"
  done
}

# chdir into the assets path directory
cd "$ASSETS_PATH"

# Wait for Kubernetes to be in a proper state
set +e
i=0
echo "Waiting for Kubernetes API..."
until $KUBECTL cluster-info; do
  i=$((i+1))
  echo "Cluster not available yet, waiting for 5 seconds ($i)"
  sleep 5
done
set -e

# wait for Kubernetes pods
wait_for_pods kube-system

echo "Creating storage class"
$KUBECTL apply -f storage-class/cinder.yaml

echo "Creating Container Linux Update Operator (cluo)"
$KUBECTL apply -f cluo/cluo-rbac.yaml
$KUBECTL apply -f cluo/update-agent.yaml
$KUBECTL apply -f cluo/update-operator.yaml

# Creating resources
echo "Creating ingress resources"
$KUBECTL apply -f ingress/ingress-rbac.yaml
$KUBECTL apply -f ingress/default-backend.yaml
$KUBECTL apply -f ingress/ingress-controller.yaml
echo "Creating dashboard app"
$KUBECTL apply -f kube-dashboard/kube-dashboard.yaml
echo "Creating kube-prometheus app"
cd "$ASSETS_PATH"/kube-prometheus
chmod +x ./deploy
./deploy
echo "Kube-apps installation is done"
exit 0
