apiVersion: v1
kind: Service
metadata:
  name: opke-etcd-cluster-client-lb
  namespace: opke
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    etcd_cluster: opke-etcd-cluster
  type: LoadBalancer