#!/bin/bash
set -e

# shellcheck disable=SC2086,SC2154
/usr/bin/docker run \
    --volume "$(pwd)":/assets \
    --volume /etc/kubernetes:/etc/kubernetes \
    --network=host \
    --entrypoint=/bin/sh \
    ${hyperkube_image}:${hyperkube_version} \
    /etc/kubernetes/addons-start /etc/kubernetes/kubeconfig /assets