#!/usr/bin/env bash

if [ -z "$${KUBECONFIG}" ]; then
    export KUBECONFIG=~/.kube/config
fi

# CAUTION - setting NAMESPACE will deploy most components to the given namespace
# however some are hardcoded to 'monitoring'. Only use if you have reviewed all manifests.

if [ -z "$${NAMESPACE}" ]; then
    NAMESPACE=opke
fi

kubectl create namespace "$NAMESPACE"

kctl() {
    kubectl --namespace "$NAMESPACE" "$@"
}

kctl apply -f manifests/etcd-operator

# Wait for CRDs to be ready.
printf "Waiting for Operator to register custom resource definitions..."
until kctl get customresourcedefinitions etcdclusters.etcd.database.coreos.com > /dev/null 2>&1; do sleep 1; printf "."; done
until kctl get etcdclusters.etcd.monitoring.coreos.com > /dev/null 2>&1; do sleep 1; printf "."; done
echo "done!"

echo "Deploying manifests"
kctl apply -f manifests/etcd
